services:
  certportal:
    build: .
    container_name: simplewebpki
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./data:/data
      - ./pki:/pki:ro
    restart: unless-stopped
